services:
  php:
    build: .
    container_name: php
    depends_on:
      - nginx
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./var/www:/var/www
    expose:
      - "9889"
    healthcheck:
      test: ["CMD", "curl", "-sSf", "http://127.0.0.1 | grep -q works"]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - network

  nginx:
    image: nginx:1-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "127.0.0.1:9889:80"
    volumes:
      - ./var/www:/var/www
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network

networks:
  network:
    driver: bridge
